# Generated by Django 4.2.6 on 2023-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
