# Generated by Django 4.2.6 on 2023-11-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_list', '0003_question_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='modified_at',
            new_name='modified_date',
        ),
    ]
